fix:  Create pages from markdown files #12
olavea/pow-site pull request #20
Opened 2022-02-07 12:34 UTC by olavea

Can I keep my comments in gatsby-node.js for my story Queen @raae ?

2022-02-07 12:51 UTC, raae commented
> Can I keep my comments in gatsby-node.js for my story Queen @raae ?

I would rather not, it's very confusing for those who are not initiated and so is the naming.

2022-02-07 12:54 UTC, raae requested changes

2022-02-07 12:54 UTC, raae commented on gatsby-node.js
> +async function bakeMarkdownNodesIntoGoodies({ graphql, actions }) {
You are making pages, not goodies. Please rename to `bakeMarkdownNodesIntoPages`.

2022-02-07 12:54 UTC, raae commented on gatsby-node.js
>    const bakingSong = require.resolve("./src/templates/bakingSong.js");
Please rename `pageTemplate`.

2022-02-07 12:54 UTC, raae commented on gatsby-node.js
>  exports.createPages = async (params) => {
Rename params `gatsbyUtils`

2022-02-07 12:54 UTC, raae commented on gatsby-node.js
>    data.supplies.nodes.forEach((ahoyGoodie) => {
You may keep supplies, but please rename ahoyGoodie to `node`.

2022-02-08 08:34 UTC, olavea commented on gatsby-node.js
> +async function bakeMarkdownNodesIntoGoodies({ graphql, actions }) {
😺 👍

2022-02-08 08:34 UTC, olavea commented on gatsby-node.js
>    const bakingSong = require.resolve("./src/templates/bakingSong.js");
😺 👍

2022-02-08 08:34 UTC, olavea commented on gatsby-node.js
>  exports.createPages = async (params) => {
😺 👍

2022-02-08 08:35 UTC, olavea commented on gatsby-node.js
>    data.supplies.nodes.forEach((ahoyGoodie) => {
😺 👍

2022-02-08 08:35 UTC, olavea commented
😺 👍

2022-02-08 09:26 UTC, merged