fix: create only markdown pages #34
olavea/pow-site pull request #43
Opened 2022-02-19 08:56 UTC by olavea

Seems to work, only create pages for markdown pages with the field: slug equals "/index/"  

```js
// POW!-website/gatsby-node.js
...
filter: { fields: { slug: { eq: "/index/" } } }

```
Screenshot of http://localhost:8000/bleh-bleh
![OlaCast-18-POW-Day-30- :index: _37](https://user-images.githubusercontent.com/7642493/154794051-534b4de9-892d-45ea-ab59-83012ffaa45f.png)

2022-02-20 08:18 UTC, raae requested changes
Looks good, need to update the page template to have the code that used to be in {MarkdownRemark.fields__slug}.js.

2022-02-20 10:32 UTC, raae commented on gatsby-node.js
> +        filter: { fields: { slug: { eq: "/index/" } } }
This will only find one page, to get all index.md files modify to: 
`allMarkdownRemark(filter: {fileAbsolutePath: {regex: "/index.md/"}}) {`

2022-02-20 10:33 UTC, raae commented on gatsby-node.js
> +        filter: { fields: { slug: { eq: "/index/" } } }
When you do this you should also see an about page being created.

2022-02-20 10:36 UTC, raae commented on gatsby-node.js
> +      path: node.fields.slug,
It seems path doesn't handle "/index/" very well.
If node.fields.slug is "/index/" use "/", or else use the node.fields.slug

2022-02-20 10:37 UTC, raae commented
Suggested steps:
1. Change the filter and make sure the about page work
2. Look into the path issue for the index page

2022-02-20 10:38 UTC, raae commented on gatsby-node.js
>    await Promise.all([slugifyMarkdownRemarkNode(gatsbyUtils)]);
No need to await or created promises here, line can be changed to: `slugifyMarkdownRemarkNode(gatsbyUtils)`

2022-02-20 10:39 UTC, raae commented on gatsby-node.js
> +  await Promise.all([bakeMarkdownNodesIntoPages(gatsbyUtils)]);
No need to await or created promises here, line can be changed to: `bakeMarkdownNodesIntoPages(gatsbyUtils)`

2022-02-21 08:53 UTC, raae commented on gatsby-node.js
> +      path: aromaNode.fields.slug,
If the slug is "/index/" then swap for "/"

2022-02-23 07:47 UTC, olavea commented on gatsby-node.js
> +      path: node.fields.slug,
```js

    //const aromaNodepath = {
    //   if (aromaNode.fields.slug === "/index/") {
    //     "/"
    // } else {
    //   aromaNode.fields.slug
    // }}
    actions.createPage({
      // A. aromaNode 🍰.🍓.🐛
      if (aromaNode.fields.slug === "/index/") {
        path:  "/"
    } else {
      path: aromaNode.fields.slug
    },
```

2022-02-23 08:45 UTC, olavea commented on gatsby-node.js
> +        filter: { fields: { slug: { eq: "/index/" } } }
😸 👍

2022-02-23 08:46 UTC, olavea commented on gatsby-node.js
> +      path: node.fields.slug,
😸 👍

2022-02-23 08:47 UTC, olavea commented on gatsby-node.js
>    await Promise.all([slugifyMarkdownRemarkNode(gatsbyUtils)]);
😸 👍

2022-02-23 08:48 UTC, olavea commented on gatsby-node.js
> +  await Promise.all([bakeMarkdownNodesIntoPages(gatsbyUtils)]);
😸 👍

2022-02-23 08:48 UTC, olavea commented on gatsby-node.js
> +      path: aromaNode.fields.slug,
😸 👍

2022-02-23 08:50 UTC, olavea commented
Can we merge?
I will delete all the comments and rename everything after my
livestream on Thursday Feb 24.

But I want to show the page as it should look at the start of the live stream

2022-02-23 09:52 UTC, raae approved these changes

2022-02-27 08:08 UTC, merged